"""Init models

Revision ID: dd7febe1cec5
Revises: 
Create Date: 2026-09-02 18:56:56.764569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7febe1cec5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('speciality', sa.String(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('preferred_branch', sa.String(), nullable=True),
    sa.Column('work_experience', sa.String(), nullable=True),
    sa.Column('previous_company', sa.String(), nullable=True),
    sa.Column('previous_position', sa.String(), nullable=True),
    sa.Column('citizenship', sa.String(), nullable=True),
    sa.Column('driving_license', sa.String(), nullable=True),
    sa.Column('health_info', sa.String(), nullable=True),
    sa.Column('expected_salary', sa.Integer(), nullable=True),
    sa.Column('criminal_record', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('additional_phone', sa.String(), nullable=True),
    sa.Column('passport_photo', sa.String(), nullable=True),
    sa.Column('personal_photo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_telegram_user_id'), 'applications', ['telegram_user_id'], unique=False)
    op.drop_index(op.f('ix_anketalar_id'), table_name='anketalar')
    op.drop_table('anketalar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anketalar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('ism', sa.VARCHAR(), nullable=True),
    sa.Column('familiya', sa.VARCHAR(), nullable=True),
    sa.Column('otasining_ismi', sa.VARCHAR(), nullable=True),
    sa.Column('tugilgan_sana', sa.VARCHAR(), nullable=True),
    sa.Column('jins', sa.VARCHAR(), nullable=True),
    sa.Column('oilaviy_holati', sa.VARCHAR(), nullable=True),
    sa.Column('malumoti', sa.VARCHAR(), nullable=True),
    sa.Column('talabami', sa.VARCHAR(), nullable=True),
    sa.Column('boy', sa.INTEGER(), nullable=True),
    sa.Column('vazn', sa.INTEGER(), nullable=True),
    sa.Column('viloyat', sa.VARCHAR(), nullable=True),
    sa.Column('tuman', sa.VARCHAR(), nullable=True),
    sa.Column('manzil_toliq', sa.VARCHAR(), nullable=True),
    sa.Column('filial', sa.VARCHAR(), nullable=True),
    sa.Column('lavozim', sa.VARCHAR(), nullable=True),
    sa.Column('avval_ishlagan', sa.VARCHAR(), nullable=True),
    sa.Column('fuqaro', sa.VARCHAR(), nullable=True),
    sa.Column('ishlaydimi', sa.VARCHAR(), nullable=True),
    sa.Column('avto', sa.VARCHAR(), nullable=True),
    sa.Column('xizmat_safari', sa.VARCHAR(), nullable=True),
    sa.Column('qarindoshlar', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_ogir_narsa', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_ogir_narsa_izoh', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_yurak', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_yurak_izoh', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_jarrohlik', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_jarrohlik_izoh', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_koz', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_koz_izoh', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_bel', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_bel_izoh', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_joyida_ishlash', sa.VARCHAR(), nullable=True),
    sa.Column('sogliq_joyida_ishlash_izoh', sa.VARCHAR(), nullable=True),
    sa.Column('oxirgi_maosh', sa.INTEGER(), nullable=True),
    sa.Column('xohlagan_maosh', sa.INTEGER(), nullable=True),
    sa.Column('qayerdan_bildi', sa.VARCHAR(), nullable=True),
    sa.Column('sudlanganlik', sa.VARCHAR(), nullable=True),
    sa.Column('qoshimcha_izoh', sa.VARCHAR(), nullable=True),
    sa.Column('qoshimcha_tel', sa.VARCHAR(), nullable=True),
    sa.Column('pasport_turi', sa.VARCHAR(), nullable=True),
    sa.Column('dynamic_lists', sa.TEXT(), nullable=True),
    sa.Column('rasm_path', sa.VARCHAR(), nullable=True),
    sa.Column('pasport_path', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anketalar_id'), 'anketalar', ['id'], unique=False)
    op.drop_index(op.f('ix_applications_telegram_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
